# Generated by Django 4.0.1 on 2022-01-10 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fuser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=32, verbose_name='syw')),
                ('password', models.CharField(max_length=64, verbose_name='1234')),
                ('register_dttm', models.DateField(auto_now_add=True, verbose_name='가입날짜')),
            ],
            options={
                'verbose_name': '사용자 모임',
                'verbose_name_plural': '사용자 모임',
                'db_table': 'user_define_fuser_table',
            },
        ),
    ]
