# Generated by Django 3.2.8 on 2022-01-11 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=64, verbose_name='사용자명')),
                ('password', models.CharField(max_length=64, verbose_name='비밀번호')),
                ('email', models.EmailField(max_length=64, verbose_name='이메일 주소')),
                ('registered_dttm', models.DateTimeField(auto_now_add=True, verbose_name='등록 시간')),
            ],
            options={
                'db_table': 'signup_user',
            },
        ),
    ]
