# Generated by Django 3.2.8 on 2022-01-12 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
        migrations.AlterModelOptions(
            name='fuser',
            options={'verbose_name': 'Signup_table', 'verbose_name_plural': '회원정보'},
        ),
        migrations.AddField(
            model_name='fuser',
            name='email',
            field=models.EmailField(max_length=64, null=True, verbose_name='이메일 주소'),
        ),
        migrations.AlterField(
            model_name='fuser',
            name='password',
            field=models.CharField(max_length=64, verbose_name='비밀번호'),
        ),
        migrations.AlterField(
            model_name='fuser',
            name='username',
            field=models.CharField(max_length=32, verbose_name='사용자명'),
        ),
        migrations.AlterModelTable(
            name='fuser',
            table='signup_users',
        ),
    ]
